version: '3.3'

services:  
  postgres:
    container_name: postgres_container
    image: postgres:14.1        
    environment:      
      POSTGRES_USER: ${TYPEORM_USER}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_NAME}
      DATABASE_TEST_NAME: ${TYPEORM_TEST_NAME}
      PGDATA: /data/postgres    
    volumes:
       - ./postgres:/data/postgres     
       - ./src/database/scripts:/docker-entrypoint-initdb.d/
     
     
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    networks:
      - postgres
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    